"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.estimate_notification_recipients_success_response import EstimateNotificationRecipientsSuccessResponse


class TestEstimateNotificationRecipientsSuccessResponse(unittest.TestCase):
    """EstimateNotificationRecipientsSuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEstimateNotificationRecipientsSuccessResponse(self):
        """Test EstimateNotificationRecipientsSuccessResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EstimateNotificationRecipientsSuccessResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
