"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.estimate_notification_recipients_request_all_of import EstimateNotificationRecipientsRequestAllOf
from onesignal.model.filter_expression import FilterExpression
from onesignal.model.include_aliases import IncludeAliases
from onesignal.model.segment_notification_target import SegmentNotificationTarget
globals()['EstimateNotificationRecipientsRequestAllOf'] = EstimateNotificationRecipientsRequestAllOf
globals()['FilterExpression'] = FilterExpression
globals()['IncludeAliases'] = IncludeAliases
globals()['SegmentNotificationTarget'] = SegmentNotificationTarget
from onesignal.model.estimate_notification_recipients_request import EstimateNotificationRecipientsRequest


class TestEstimateNotificationRecipientsRequest(unittest.TestCase):
    """EstimateNotificationRecipientsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEstimateNotificationRecipientsRequest(self):
        """Test EstimateNotificationRecipientsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EstimateNotificationRecipientsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
