"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.api_key_token import ApiKeyToken
globals()['ApiKeyToken'] = ApiKeyToken
from onesignal.model.api_key_tokens_list_response import ApiKeyTokensListResponse


class TestApiKeyTokensListResponse(unittest.TestCase):
    """ApiKeyTokensListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiKeyTokensListResponse(self):
        """Test ApiKeyTokensListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiKeyTokensListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
