"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.2.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.create_segment_success_response import CreateSegmentSuccessResponse


class TestCreateSegmentSuccessResponse(unittest.TestCase):
    """CreateSegmentSuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateSegmentSuccessResponse(self):
        """Test CreateSegmentSuccessResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateSegmentSuccessResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
