"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.audit_log_target import AuditLogTarget


class TestAuditLogTarget(unittest.TestCase):
    """AuditLogTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuditLogTarget(self):
        """Test AuditLogTarget"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuditLogTarget()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
