"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.2.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.filter import Filter
from onesignal.model.operator import Operator
globals()['Filter'] = Filter
globals()['Operator'] = Operator
from onesignal.model.filter_expression import FilterExpression


class TestFilterExpression(unittest.TestCase):
    """FilterExpression unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterExpression(self):
        """Test FilterExpression"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FilterExpression()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
