"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.include_aliases import IncludeAliases


class TestIncludeAliases(unittest.TestCase):
    """IncludeAliases unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncludeAliases(self):
        """Test IncludeAliases"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IncludeAliases()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
