"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.journey_audience import JourneyAudience
from onesignal.model.journey_early_exit import JourneyEarlyExit
from onesignal.model.journey_node import JourneyNode
from onesignal.model.journey_reentry_rules import JourneyReentryRules
from onesignal.model.journey_schedule import JourneySchedule
globals()['JourneyAudience'] = JourneyAudience
globals()['JourneyEarlyExit'] = JourneyEarlyExit
globals()['JourneyNode'] = JourneyNode
globals()['JourneyReentryRules'] = JourneyReentryRules
globals()['JourneySchedule'] = JourneySchedule
from onesignal.model.update_journey_request import UpdateJourneyRequest


class TestUpdateJourneyRequest(unittest.TestCase):
    """UpdateJourneyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateJourneyRequest(self):
        """Test UpdateJourneyRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateJourneyRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
