"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.delete_player_bad_request_response import DeletePlayerBadRequestResponse


class TestDeletePlayerBadRequestResponse(unittest.TestCase):
    """DeletePlayerBadRequestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeletePlayerBadRequestResponse(self):
        """Test DeletePlayerBadRequestResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeletePlayerBadRequestResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
