"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.2.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.create_user_conflict_response_errors_items_meta import CreateUserConflictResponseErrorsItemsMeta
globals()['CreateUserConflictResponseErrorsItemsMeta'] = CreateUserConflictResponseErrorsItemsMeta
from onesignal.model.create_user_conflict_response_errors_inner import CreateUserConflictResponseErrorsInner


class TestCreateUserConflictResponseErrorsInner(unittest.TestCase):
    """CreateUserConflictResponseErrorsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateUserConflictResponseErrorsInner(self):
        """Test CreateUserConflictResponseErrorsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateUserConflictResponseErrorsInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
