"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.filter_expression import FilterExpression
from onesignal.model.include_aliases import IncludeAliases
from onesignal.model.language_string_map import LanguageStringMap
globals()['FilterExpression'] = FilterExpression
globals()['IncludeAliases'] = IncludeAliases
globals()['LanguageStringMap'] = LanguageStringMap
from onesignal.model.start_live_activity_request import StartLiveActivityRequest


class TestStartLiveActivityRequest(unittest.TestCase):
    """StartLiveActivityRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStartLiveActivityRequest(self):
        """Test StartLiveActivityRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StartLiveActivityRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
