"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.2.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import onesignal
from onesignal.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_notification(self):
        """Test case for cancel_notification

        Stop a scheduled or currently outgoing notification  # noqa: E501
        """
        pass

    def test_create_alias(self):
        """Test case for create_alias

        """
        pass

    def test_create_alias_by_subscription(self):
        """Test case for create_alias_by_subscription

        """
        pass

    def test_create_app(self):
        """Test case for create_app

        Create an app  # noqa: E501
        """
        pass

    def test_create_notification(self):
        """Test case for create_notification

        Create notification  # noqa: E501
        """
        pass

    def test_create_segment(self):
        """Test case for create_segment

        Create Segment  # noqa: E501
        """
        pass

    def test_create_subscription(self):
        """Test case for create_subscription

        """
        pass

    def test_create_user(self):
        """Test case for create_user

        """
        pass

    def test_delete_alias(self):
        """Test case for delete_alias

        """
        pass

    def test_delete_segment(self):
        """Test case for delete_segment

        Delete Segment  # noqa: E501
        """
        pass

    def test_delete_subscription(self):
        """Test case for delete_subscription

        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        """
        pass

    def test_export_events(self):
        """Test case for export_events

        Export CSV of Events  # noqa: E501
        """
        pass

    def test_export_subscriptions(self):
        """Test case for export_subscriptions

        Export CSV of Subscriptions  # noqa: E501
        """
        pass

    def test_get_aliases(self):
        """Test case for get_aliases

        """
        pass

    def test_get_aliases_by_subscription(self):
        """Test case for get_aliases_by_subscription

        """
        pass

    def test_get_app(self):
        """Test case for get_app

        View an app  # noqa: E501
        """
        pass

    def test_get_apps(self):
        """Test case for get_apps

        View apps  # noqa: E501
        """
        pass

    def test_get_notification(self):
        """Test case for get_notification

        View notification  # noqa: E501
        """
        pass

    def test_get_notification_history(self):
        """Test case for get_notification_history

        Notification History  # noqa: E501
        """
        pass

    def test_get_notifications(self):
        """Test case for get_notifications

        View notifications  # noqa: E501
        """
        pass

    def test_get_outcomes(self):
        """Test case for get_outcomes

        View Outcomes  # noqa: E501
        """
        pass

    def test_get_segments(self):
        """Test case for get_segments

        Get Segments  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        """
        pass

    def test_transfer_subscription(self):
        """Test case for transfer_subscription

        """
        pass

    def test_unsubscribe_email_with_token(self):
        """Test case for unsubscribe_email_with_token

        Unsubscribe with token  # noqa: E501
        """
        pass

    def test_update_app(self):
        """Test case for update_app

        Update an app  # noqa: E501
        """
        pass

    def test_update_live_activity(self):
        """Test case for update_live_activity

        Update a Live Activity via Push  # noqa: E501
        """
        pass

    def test_update_subscription(self):
        """Test case for update_subscription

        """
        pass

    def test_update_user(self):
        """Test case for update_user

        """
        pass


if __name__ == '__main__':
    unittest.main()
