"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.player import Player
globals()['Player'] = Player
from onesignal.model.players import Players


class TestPlayers(unittest.TestCase):
    """Players unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayers(self):
        """Test Players"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Players()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
