"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.email_reputation_window import EmailReputationWindow
globals()['EmailReputationWindow'] = EmailReputationWindow
from onesignal.model.email_reputation_response import EmailReputationResponse


class TestEmailReputationResponse(unittest.TestCase):
    """EmailReputationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmailReputationResponse(self):
        """Test EmailReputationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmailReputationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
