"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.basic_notification_all_of import BasicNotificationAllOf
from onesignal.model.basic_notification_all_of_android_background_layout import BasicNotificationAllOfAndroidBackgroundLayout
from onesignal.model.button import Button
from onesignal.model.filter import Filter
from onesignal.model.notification_target import NotificationTarget
from onesignal.model.player_notification_target_include_aliases import PlayerNotificationTargetIncludeAliases
from onesignal.model.string_map import StringMap
globals()['BasicNotificationAllOf'] = BasicNotificationAllOf
globals()['BasicNotificationAllOfAndroidBackgroundLayout'] = BasicNotificationAllOfAndroidBackgroundLayout
globals()['Button'] = Button
globals()['Filter'] = Filter
globals()['NotificationTarget'] = NotificationTarget
globals()['PlayerNotificationTargetIncludeAliases'] = PlayerNotificationTargetIncludeAliases
globals()['StringMap'] = StringMap
from onesignal.model.basic_notification import BasicNotification


class TestBasicNotification(unittest.TestCase):
    """BasicNotification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBasicNotification(self):
        """Test BasicNotification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BasicNotification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
