"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.custom_event import CustomEvent
globals()['CustomEvent'] = CustomEvent
from onesignal.model.custom_events_request import CustomEventsRequest


class TestCustomEventsRequest(unittest.TestCase):
    """CustomEventsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomEventsRequest(self):
        """Test CustomEventsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomEventsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
