"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.template_resource import TemplateResource
globals()['TemplateResource'] = TemplateResource
from onesignal.model.templates_list_response import TemplatesListResponse


class TestTemplatesListResponse(unittest.TestCase):
    """TemplatesListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTemplatesListResponse(self):
        """Test TemplatesListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TemplatesListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
