"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.journey_list_audience import JourneyListAudience
from onesignal.model.journey_reentry_rules import JourneyReentryRules
from onesignal.model.journey_schedule import JourneySchedule
globals()['JourneyListAudience'] = JourneyListAudience
globals()['JourneyReentryRules'] = JourneyReentryRules
globals()['JourneySchedule'] = JourneySchedule
from onesignal.model.journey_list_item import JourneyListItem


class TestJourneyListItem(unittest.TestCase):
    """JourneyListItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJourneyListItem(self):
        """Test JourneyListItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JourneyListItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
