"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.journey_branch_stats import JourneyBranchStats
from onesignal.model.journey_node_stats import JourneyNodeStats
globals()['JourneyBranchStats'] = JourneyBranchStats
globals()['JourneyNodeStats'] = JourneyNodeStats
from onesignal.model.journey_stats import JourneyStats


class TestJourneyStats(unittest.TestCase):
    """JourneyStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJourneyStats(self):
        """Test JourneyStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JourneyStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
