"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.2.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.properties_deltas import PropertiesDeltas
from onesignal.model.properties_object import PropertiesObject
globals()['PropertiesDeltas'] = PropertiesDeltas
globals()['PropertiesObject'] = PropertiesObject
from onesignal.model.update_user_request import UpdateUserRequest


class TestUpdateUserRequest(unittest.TestCase):
    """UpdateUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateUserRequest(self):
        """Test UpdateUserRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateUserRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
