"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.identity_object import IdentityObject
globals()['IdentityObject'] = IdentityObject
from onesignal.model.user_identity_request_body import UserIdentityRequestBody


class TestUserIdentityRequestBody(unittest.TestCase):
    """UserIdentityRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserIdentityRequestBody(self):
        """Test UserIdentityRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserIdentityRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
