"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.2.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.create_user_conflict_response_errors_inner import CreateUserConflictResponseErrorsInner
globals()['CreateUserConflictResponseErrorsInner'] = CreateUserConflictResponseErrorsInner
from onesignal.model.create_user_conflict_response import CreateUserConflictResponse


class TestCreateUserConflictResponse(unittest.TestCase):
    """CreateUserConflictResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateUserConflictResponse(self):
        """Test CreateUserConflictResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateUserConflictResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
