"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.email_warm_up_stage import EmailWarmUpStage
globals()['EmailWarmUpStage'] = EmailWarmUpStage
from onesignal.model.email_warm_up import EmailWarmUp


class TestEmailWarmUp(unittest.TestCase):
    """EmailWarmUp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmailWarmUp(self):
        """Test EmailWarmUp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmailWarmUp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
