"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.journey_list_item import JourneyListItem
globals()['JourneyListItem'] = JourneyListItem
from onesignal.model.journey_list_response import JourneyListResponse


class TestJourneyListResponse(unittest.TestCase):
    """JourneyListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJourneyListResponse(self):
        """Test JourneyListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JourneyListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
