"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.journey_early_exit_rules_on_event import JourneyEarlyExitRulesOnEvent
from onesignal.model.journey_early_exit_rules_on_segment import JourneyEarlyExitRulesOnSegment
globals()['JourneyEarlyExitRulesOnEvent'] = JourneyEarlyExitRulesOnEvent
globals()['JourneyEarlyExitRulesOnSegment'] = JourneyEarlyExitRulesOnSegment
from onesignal.model.journey_early_exit_rules import JourneyEarlyExitRules


class TestJourneyEarlyExitRules(unittest.TestCase):
    """JourneyEarlyExitRules unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJourneyEarlyExitRules(self):
        """Test JourneyEarlyExitRules"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JourneyEarlyExitRules()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
