"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.2.2
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.cancel_notification_success_response import CancelNotificationSuccessResponse


class TestCancelNotificationSuccessResponse(unittest.TestCase):
    """CancelNotificationSuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCancelNotificationSuccessResponse(self):
        """Test CancelNotificationSuccessResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CancelNotificationSuccessResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
