"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.journey_branch import JourneyBranch
from onesignal.model.journey_time_window import JourneyTimeWindow
from onesignal.model.journey_wait_until_expiration import JourneyWaitUntilExpiration
globals()['JourneyBranch'] = JourneyBranch
globals()['JourneyTimeWindow'] = JourneyTimeWindow
globals()['JourneyWaitUntilExpiration'] = JourneyWaitUntilExpiration
from onesignal.model.update_journey_node_request import UpdateJourneyNodeRequest


class TestUpdateJourneyNodeRequest(unittest.TestCase):
    """UpdateJourneyNodeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateJourneyNodeRequest(self):
        """Test UpdateJourneyNodeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateJourneyNodeRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
