"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.create_api_key_request import CreateApiKeyRequest


class TestCreateApiKeyRequest(unittest.TestCase):
    """CreateApiKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateApiKeyRequest(self):
        """Test CreateApiKeyRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateApiKeyRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
