"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.no_subscribers_error import NoSubscribersError


class TestNoSubscribersError(unittest.TestCase):
    """NoSubscribersError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNoSubscribersError(self):
        """Test NoSubscribersError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NoSubscribersError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
