"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.properties_object import PropertiesObject
globals()['PropertiesObject'] = PropertiesObject
from onesignal.model.inline_response202 import InlineResponse202


class TestInlineResponse202(unittest.TestCase):
    """InlineResponse202 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse202(self):
        """Test InlineResponse202"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse202()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
