"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.2.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.update_live_activity_success_response import UpdateLiveActivitySuccessResponse


class TestUpdateLiveActivitySuccessResponse(unittest.TestCase):
    """UpdateLiveActivitySuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateLiveActivitySuccessResponse(self):
        """Test UpdateLiveActivitySuccessResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateLiveActivitySuccessResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
