"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.2.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.basic_notification_all_of import BasicNotificationAllOf
from onesignal.model.basic_notification_all_of_android_background_layout import BasicNotificationAllOfAndroidBackgroundLayout
from onesignal.model.button import Button
from onesignal.model.filter_expression import FilterExpression
from onesignal.model.language_string_map import LanguageStringMap
from onesignal.model.notification_target import NotificationTarget
from onesignal.model.web_button import WebButton
globals()['BasicNotificationAllOf'] = BasicNotificationAllOf
globals()['BasicNotificationAllOfAndroidBackgroundLayout'] = BasicNotificationAllOfAndroidBackgroundLayout
globals()['Button'] = Button
globals()['FilterExpression'] = FilterExpression
globals()['LanguageStringMap'] = LanguageStringMap
globals()['NotificationTarget'] = NotificationTarget
globals()['WebButton'] = WebButton
from onesignal.model.basic_notification import BasicNotification


class TestBasicNotification(unittest.TestCase):
    """BasicNotification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBasicNotification(self):
        """Test BasicNotification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BasicNotification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
