"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.basic_notification import BasicNotification
from onesignal.model.basic_notification_all_of_android_background_layout import BasicNotificationAllOfAndroidBackgroundLayout
from onesignal.model.button import Button
from onesignal.model.delivery_data import DeliveryData
from onesignal.model.filter import Filter
from onesignal.model.notification_with_meta_all_of import NotificationWithMetaAllOf
from onesignal.model.outcome_data import OutcomeData
from onesignal.model.outcomes_data import OutcomesData
from onesignal.model.platform_delivery_data import PlatformDeliveryData
from onesignal.model.string_map import StringMap
globals()['BasicNotification'] = BasicNotification
globals()['BasicNotificationAllOfAndroidBackgroundLayout'] = BasicNotificationAllOfAndroidBackgroundLayout
globals()['Button'] = Button
globals()['DeliveryData'] = DeliveryData
globals()['Filter'] = Filter
globals()['NotificationWithMetaAllOf'] = NotificationWithMetaAllOf
globals()['OutcomeData'] = OutcomeData
globals()['OutcomesData'] = OutcomesData
globals()['PlatformDeliveryData'] = PlatformDeliveryData
globals()['StringMap'] = StringMap
from onesignal.model.notification_with_meta import NotificationWithMeta


class TestNotificationWithMeta(unittest.TestCase):
    """NotificationWithMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationWithMeta(self):
        """Test NotificationWithMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotificationWithMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
