"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.2.2
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.generic_error_errors_inner import GenericErrorErrorsInner


class TestGenericErrorErrorsInner(unittest.TestCase):
    """GenericErrorErrorsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenericErrorErrorsInner(self):
        """Test GenericErrorErrorsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GenericErrorErrorsInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
