"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.player import Player


class TestPlayer(unittest.TestCase):
    """Player unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayer(self):
        """Test Player"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Player()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
