"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.3.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.language_string_map import LanguageStringMap
globals()['LanguageStringMap'] = LanguageStringMap
from onesignal.model.update_template_request import UpdateTemplateRequest


class TestUpdateTemplateRequest(unittest.TestCase):
    """UpdateTemplateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateTemplateRequest(self):
        """Test UpdateTemplateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateTemplateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
