"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.2.2
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.subscription_object import SubscriptionObject
globals()['SubscriptionObject'] = SubscriptionObject
from onesignal.model.inline_response201 import InlineResponse201


class TestInlineResponse201(unittest.TestCase):
    """InlineResponse201 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse201(self):
        """Test InlineResponse201"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse201()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
