"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.identity_object import IdentityObject
globals()['IdentityObject'] = IdentityObject
from onesignal.model.user_identity_response import UserIdentityResponse


class TestUserIdentityResponse(unittest.TestCase):
    """UserIdentityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserIdentityResponse(self):
        """Test UserIdentityResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserIdentityResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
