"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.segment_details import SegmentDetails
globals()['SegmentDetails'] = SegmentDetails
from onesignal.model.get_segment_success_response import GetSegmentSuccessResponse


class TestGetSegmentSuccessResponse(unittest.TestCase):
    """GetSegmentSuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSegmentSuccessResponse(self):
        """Test GetSegmentSuccessResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetSegmentSuccessResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
