"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.filter_expression import FilterExpression
from onesignal.model.include_aliases import IncludeAliases
globals()['FilterExpression'] = FilterExpression
globals()['IncludeAliases'] = IncludeAliases
from onesignal.model.estimate_notification_recipients_request_all_of import EstimateNotificationRecipientsRequestAllOf


class TestEstimateNotificationRecipientsRequestAllOf(unittest.TestCase):
    """EstimateNotificationRecipientsRequestAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEstimateNotificationRecipientsRequestAllOf(self):
        """Test EstimateNotificationRecipientsRequestAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EstimateNotificationRecipientsRequestAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
