"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.2.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.platform_delivery_data import PlatformDeliveryData
globals()['PlatformDeliveryData'] = PlatformDeliveryData
from onesignal.model.notification_with_meta_all_of import NotificationWithMetaAllOf


class TestNotificationWithMetaAllOf(unittest.TestCase):
    """NotificationWithMetaAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationWithMetaAllOf(self):
        """Test NotificationWithMetaAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotificationWithMetaAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
