"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.journey_time_point import JourneyTimePoint


class TestJourneyTimePoint(unittest.TestCase):
    """JourneyTimePoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJourneyTimePoint(self):
        """Test JourneyTimePoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JourneyTimePoint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
