"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.inline_response2003 import InlineResponse2003


class TestInlineResponse2003(unittest.TestCase):
    """InlineResponse2003 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003(self):
        """Test InlineResponse2003"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2003()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
