"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.journey_event_trigger_attributes import JourneyEventTriggerAttributes
globals()['JourneyEventTriggerAttributes'] = JourneyEventTriggerAttributes
from onesignal.model.journey_condition import JourneyCondition


class TestJourneyCondition(unittest.TestCase):
    """JourneyCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJourneyCondition(self):
        """Test JourneyCondition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JourneyCondition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
