"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.journey_condition import JourneyCondition
from onesignal.model.journey_node import JourneyNode
globals()['JourneyCondition'] = JourneyCondition
globals()['JourneyNode'] = JourneyNode
from onesignal.model.journey_branch import JourneyBranch


class TestJourneyBranch(unittest.TestCase):
    """JourneyBranch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJourneyBranch(self):
        """Test JourneyBranch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JourneyBranch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
