"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.update_player_tags_request_body import UpdatePlayerTagsRequestBody


class TestUpdatePlayerTagsRequestBody(unittest.TestCase):
    """UpdatePlayerTagsRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdatePlayerTagsRequestBody(self):
        """Test UpdatePlayerTagsRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdatePlayerTagsRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
