"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.2.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.outcome_data import OutcomeData
globals()['OutcomeData'] = OutcomeData
from onesignal.model.outcomes_data import OutcomesData


class TestOutcomesData(unittest.TestCase):
    """OutcomesData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutcomesData(self):
        """Test OutcomesData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OutcomesData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
