"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.journey_event_attribute import JourneyEventAttribute
globals()['JourneyEventAttribute'] = JourneyEventAttribute
from onesignal.model.journey_event_trigger_attributes import JourneyEventTriggerAttributes


class TestJourneyEventTriggerAttributes(unittest.TestCase):
    """JourneyEventTriggerAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJourneyEventTriggerAttributes(self):
        """Test JourneyEventTriggerAttributes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JourneyEventTriggerAttributes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
