"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.filter_expression import FilterExpression
globals()['FilterExpression'] = FilterExpression
from onesignal.model.segment_details import SegmentDetails


class TestSegmentDetails(unittest.TestCase):
    """SegmentDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSegmentDetails(self):
        """Test SegmentDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SegmentDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
