"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.2.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.app import App
globals()['App'] = App
from onesignal.model.apps import Apps


class TestApps(unittest.TestCase):
    """Apps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApps(self):
        """Test Apps"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Apps()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
