"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.filter import Filter
from onesignal.model.operator import Operator
globals()['Filter'] = Filter
globals()['Operator'] = Operator
from onesignal.model.filter_expressions import FilterExpressions


class TestFilterExpressions(unittest.TestCase):
    """FilterExpressions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterExpressions(self):
        """Test FilterExpressions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FilterExpressions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
