"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.filter_expression import FilterExpression
globals()['FilterExpression'] = FilterExpression
from onesignal.model.update_segment_request import UpdateSegmentRequest


class TestUpdateSegmentRequest(unittest.TestCase):
    """UpdateSegmentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateSegmentRequest(self):
        """Test UpdateSegmentRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateSegmentRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
