"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.audit_log_event import AuditLogEvent
globals()['AuditLogEvent'] = AuditLogEvent
from onesignal.model.list_audit_logs_success_response import ListAuditLogsSuccessResponse


class TestListAuditLogsSuccessResponse(unittest.TestCase):
    """ListAuditLogsSuccessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAuditLogsSuccessResponse(self):
        """Test ListAuditLogsSuccessResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListAuditLogsSuccessResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
