"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.2.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.identity_object import IdentityObject
globals()['IdentityObject'] = IdentityObject
from onesignal.model.user_identity_body import UserIdentityBody


class TestUserIdentityBody(unittest.TestCase):
    """UserIdentityBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserIdentityBody(self):
        """Test UserIdentityBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserIdentityBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
