"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.delete_player_not_found_response import DeletePlayerNotFoundResponse


class TestDeletePlayerNotFoundResponse(unittest.TestCase):
    """DeletePlayerNotFoundResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeletePlayerNotFoundResponse(self):
        """Test DeletePlayerNotFoundResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeletePlayerNotFoundResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
