"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.duplicate_journey_overrides import DuplicateJourneyOverrides
globals()['DuplicateJourneyOverrides'] = DuplicateJourneyOverrides
from onesignal.model.duplicate_journey_request import DuplicateJourneyRequest


class TestDuplicateJourneyRequest(unittest.TestCase):
    """DuplicateJourneyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDuplicateJourneyRequest(self):
        """Test DuplicateJourneyRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DuplicateJourneyRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
