"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.2.1
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.identify_user_conflict_response_errors_inner import IdentifyUserConflictResponseErrorsInner


class TestIdentifyUserConflictResponseErrorsInner(unittest.TestCase):
    """IdentifyUserConflictResponseErrorsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentifyUserConflictResponseErrorsInner(self):
        """Test IdentifyUserConflictResponseErrorsInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IdentifyUserConflictResponseErrorsInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
