"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.11.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.audit_log_actor import AuditLogActor
from onesignal.model.audit_log_context import AuditLogContext
from onesignal.model.audit_log_target import AuditLogTarget
globals()['AuditLogActor'] = AuditLogActor
globals()['AuditLogContext'] = AuditLogContext
globals()['AuditLogTarget'] = AuditLogTarget
from onesignal.model.audit_log_event import AuditLogEvent


class TestAuditLogEvent(unittest.TestCase):
    """AuditLogEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuditLogEvent(self):
        """Test AuditLogEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuditLogEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
