"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.4.1
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.player import Player
globals()['Player'] = Player
from onesignal.model.player_slice import PlayerSlice


class TestPlayerSlice(unittest.TestCase):
    """PlayerSlice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerSlice(self):
        """Test PlayerSlice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PlayerSlice()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
