"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.journey_message_stats import JourneyMessageStats
globals()['JourneyMessageStats'] = JourneyMessageStats
from onesignal.model.journey_node_stats import JourneyNodeStats


class TestJourneyNodeStats(unittest.TestCase):
    """JourneyNodeStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJourneyNodeStats(self):
        """Test JourneyNodeStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JourneyNodeStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
