"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.2.2
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.invalid_identifier_error import InvalidIdentifierError
from onesignal.model.no_subscribers_error import NoSubscribersError
globals()['InvalidIdentifierError'] = InvalidIdentifierError
globals()['NoSubscribersError'] = NoSubscribersError
from onesignal.model.notification200_errors import Notification200Errors


class TestNotification200Errors(unittest.TestCase):
    """Notification200Errors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotification200Errors(self):
        """Test Notification200Errors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Notification200Errors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
