"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 1.4.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import onesignal
from onesignal.model.export_players_request_body import ExportPlayersRequestBody


class TestExportPlayersRequestBody(unittest.TestCase):
    """ExportPlayersRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExportPlayersRequestBody(self):
        """Test ExportPlayersRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExportPlayersRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
