# flake8: noqa

"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.9.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "5.9.0"

# import ApiClient
from onesignal.api_client import ApiClient

# import Configuration
from onesignal.configuration import Configuration

# import exceptions
from onesignal.exceptions import OpenApiException
from onesignal.exceptions import ApiAttributeError
from onesignal.exceptions import ApiTypeError
from onesignal.exceptions import ApiValueError
from onesignal.exceptions import ApiKeyError
from onesignal.exceptions import ApiException

# import helpers
from onesignal.helpers import CreateNotificationWithRetryResult
from onesignal.helpers import create_notification_with_retry

# OneSignal: surface the idempotent-retry helper as a DefaultApi method so the
# call mirrors create_notification. The function's first parameter (api) binds
# as self; helpers.py stays the single source of truth.
from onesignal.api.default_api import DefaultApi as _DefaultApi
_DefaultApi.create_notification_with_retry = create_notification_with_retry
from onesignal.errors import OneSignalErrors
