# flake8: noqa

"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    The version of the OpenAPI document: 5.2.0
    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "5.2.0-beta1"

# import ApiClient
from onesignal.api_client import ApiClient

# import Configuration
from onesignal.configuration import Configuration

# import exceptions
from onesignal.exceptions import OpenApiException
from onesignal.exceptions import ApiAttributeError
from onesignal.exceptions import ApiTypeError
from onesignal.exceptions import ApiValueError
from onesignal.exceptions import ApiKeyError
from onesignal.exceptions import ApiException
