"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from onesignal.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from onesignal.exceptions import ApiAttributeError


def lazy_import():
    from onesignal.model.journey_audience import JourneyAudience
    from onesignal.model.journey_early_exit import JourneyEarlyExit
    from onesignal.model.journey_node import JourneyNode
    from onesignal.model.journey_reentry_rules import JourneyReentryRules
    from onesignal.model.journey_schedule import JourneySchedule
    globals()['JourneyAudience'] = JourneyAudience
    globals()['JourneyEarlyExit'] = JourneyEarlyExit
    globals()['JourneyNode'] = JourneyNode
    globals()['JourneyReentryRules'] = JourneyReentryRules
    globals()['JourneySchedule'] = JourneySchedule


class Journey(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('state',): {
            'DRAFT': "draft",
            'SCHEDULED': "scheduled",
            'PROCESSING': "processing",
            'ACTIVE': "active",
            'ARCHIVED': "archived",
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (str,),  # noqa: E501
            'app_id': (str,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'description': (str, none_type,),  # noqa: E501
            'state': (str,),  # noqa: E501
            'created_at': (str,),  # noqa: E501
            'updated_at': (str,),  # noqa: E501
            'started_at': (str, none_type,),  # noqa: E501
            'archived_at': (str, none_type,),  # noqa: E501
            'created_source': (str, none_type,),  # noqa: E501
            'audience': (JourneyAudience,),  # noqa: E501
            'early_exit': (JourneyEarlyExit,),  # noqa: E501
            'reentry_rules': (JourneyReentryRules,),  # noqa: E501
            'schedule': (JourneySchedule,),  # noqa: E501
            'nodes': ([JourneyNode],),  # noqa: E501
            'concurrency_key': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'app_id': 'app_id',  # noqa: E501
        'name': 'name',  # noqa: E501
        'description': 'description',  # noqa: E501
        'state': 'state',  # noqa: E501
        'created_at': 'created_at',  # noqa: E501
        'updated_at': 'updated_at',  # noqa: E501
        'started_at': 'started_at',  # noqa: E501
        'archived_at': 'archived_at',  # noqa: E501
        'created_source': 'created_source',  # noqa: E501
        'audience': 'audience',  # noqa: E501
        'early_exit': 'early_exit',  # noqa: E501
        'reentry_rules': 'reentry_rules',  # noqa: E501
        'schedule': 'schedule',  # noqa: E501
        'nodes': 'nodes',  # noqa: E501
        'concurrency_key': 'concurrency_key',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """Journey - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): Journey UUID. Read-only.. [optional]  # noqa: E501
            app_id (str): UUID of the app the journey belongs to. Read-only.. [optional]  # noqa: E501
            name (str): Journey name, up to 300 characters.. [optional]  # noqa: E501
            description (str, none_type): Journey description, up to 1024 characters. Defaults to an empty string.. [optional]  # noqa: E501
            state (str): Journey state. New journeys are created as draft. processing is transient while activation is in progress. archived is a journey that has been stopped. Change it through the state field on Update journey.. [optional]  # noqa: E501
            created_at (str): ISO 8601 creation time. Read-only.. [optional]  # noqa: E501
            updated_at (str): ISO 8601 last-update time. Read-only.. [optional]  # noqa: E501
            started_at (str, none_type): ISO 8601 time the journey was activated, or null. Read-only. May stay null briefly after you set state to active: activation is enqueued, and started_at populates once the journey finishes processing.. [optional]  # noqa: E501
            archived_at (str, none_type): ISO 8601 time the journey was archived, or null. Read-only.. [optional]  # noqa: E501
            created_source (str, none_type): Origin of the journey, for example public_api or dashboard. Read-only.. [optional]  # noqa: E501
            audience (JourneyAudience): [optional]  # noqa: E501
            early_exit (JourneyEarlyExit): [optional]  # noqa: E501
            reentry_rules (JourneyReentryRules): [optional]  # noqa: E501
            schedule (JourneySchedule): [optional]  # noqa: E501
            nodes ([JourneyNode]): Ordered list of journey nodes.. [optional]  # noqa: E501
            concurrency_key (str): Opaque optimistic-concurrency token. Read-only. Pass it back on update to guard against overwriting a concurrent change (409). Send it back exactly as read; do not construct or parse it.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Journey - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): Journey UUID. Read-only.. [optional]  # noqa: E501
            app_id (str): UUID of the app the journey belongs to. Read-only.. [optional]  # noqa: E501
            name (str): Journey name, up to 300 characters.. [optional]  # noqa: E501
            description (str, none_type): Journey description, up to 1024 characters. Defaults to an empty string.. [optional]  # noqa: E501
            state (str): Journey state. New journeys are created as draft. processing is transient while activation is in progress. archived is a journey that has been stopped. Change it through the state field on Update journey.. [optional]  # noqa: E501
            created_at (str): ISO 8601 creation time. Read-only.. [optional]  # noqa: E501
            updated_at (str): ISO 8601 last-update time. Read-only.. [optional]  # noqa: E501
            started_at (str, none_type): ISO 8601 time the journey was activated, or null. Read-only. May stay null briefly after you set state to active: activation is enqueued, and started_at populates once the journey finishes processing.. [optional]  # noqa: E501
            archived_at (str, none_type): ISO 8601 time the journey was archived, or null. Read-only.. [optional]  # noqa: E501
            created_source (str, none_type): Origin of the journey, for example public_api or dashboard. Read-only.. [optional]  # noqa: E501
            audience (JourneyAudience): [optional]  # noqa: E501
            early_exit (JourneyEarlyExit): [optional]  # noqa: E501
            reentry_rules (JourneyReentryRules): [optional]  # noqa: E501
            schedule (JourneySchedule): [optional]  # noqa: E501
            nodes ([JourneyNode]): Ordered list of journey nodes.. [optional]  # noqa: E501
            concurrency_key (str): Opaque optimistic-concurrency token. Read-only. Pass it back on update to guard against overwriting a concurrent change (409). Send it back exactly as read; do not construct or parse it.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
