"""
    OneSignal

    A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com  # noqa: E501

    Contact: devrel@onesignal.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from onesignal.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from onesignal.exceptions import ApiAttributeError


def lazy_import():
    from onesignal.model.journey_branch import JourneyBranch
    from onesignal.model.journey_time_window import JourneyTimeWindow
    from onesignal.model.journey_wait_until_expiration import JourneyWaitUntilExpiration
    globals()['JourneyBranch'] = JourneyBranch
    globals()['JourneyTimeWindow'] = JourneyTimeWindow
    globals()['JourneyWaitUntilExpiration'] = JourneyWaitUntilExpiration


class UpdateJourneyNodeRequest(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('relative_to',): {
            'SCHEDULE_IN_TIMEZONE': "schedule_in_timezone",
            'LAST_ACTIVE_TIME': "last_active_time",
        },
    }

    validations = {
        ('duration_seconds',): {
            'inclusive_maximum': 31556952,
            'inclusive_minimum': 60,
        },
        ('user_ttl_seconds',): {
            'inclusive_minimum': 1,
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'client_node_id': (str,),  # noqa: E501
            'annotation': (str,),  # noqa: E501
            'duration_seconds': (int, none_type,),  # noqa: E501
            'relative_to': (str,),  # noqa: E501
            'windows': ([JourneyTimeWindow],),  # noqa: E501
            'time_zone': (str,),  # noqa: E501
            'use_user_time_zone': (bool, none_type,),  # noqa: E501
            'template_id': (str,),  # noqa: E501
            'iam_id': (str,),  # noqa: E501
            'user_ttl_seconds': (int, none_type,),  # noqa: E501
            'webhook_id': (str,),  # noqa: E501
            'assignments': ({str: (str,)},),  # noqa: E501
            'randomize_on_entry': (bool, none_type,),  # noqa: E501
            'branches': ([JourneyBranch],),  # noqa: E501
            'expiration': (JourneyWaitUntilExpiration,),  # noqa: E501
            'concurrency_key': (str, none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'client_node_id': 'client_node_id',  # noqa: E501
        'annotation': 'annotation',  # noqa: E501
        'duration_seconds': 'duration_seconds',  # noqa: E501
        'relative_to': 'relative_to',  # noqa: E501
        'windows': 'windows',  # noqa: E501
        'time_zone': 'time_zone',  # noqa: E501
        'use_user_time_zone': 'use_user_time_zone',  # noqa: E501
        'template_id': 'template_id',  # noqa: E501
        'iam_id': 'iam_id',  # noqa: E501
        'user_ttl_seconds': 'user_ttl_seconds',  # noqa: E501
        'webhook_id': 'webhook_id',  # noqa: E501
        'assignments': 'assignments',  # noqa: E501
        'randomize_on_entry': 'randomize_on_entry',  # noqa: E501
        'branches': 'branches',  # noqa: E501
        'expiration': 'expiration',  # noqa: E501
        'concurrency_key': 'concurrency_key',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """UpdateJourneyNodeRequest - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            client_node_id (str): Optional client-assigned identifier, unique within the journey. Use it to reference this node from elsewhere in the same request. Persisted and returned on reads.. [optional]  # noqa: E501
            annotation (str): Optional free-text label, up to 255 characters. Stored and returned as-is with no effect on journey behavior.. [optional]  # noqa: E501
            duration_seconds (int, none_type): wait nodes: seconds to hold the user. Minimum 60, maximum 31556952 (1 year).. [optional]  # noqa: E501
            relative_to (str): time_window nodes: schedule_in_timezone uses the configured windows; last_active_time holds relative to the user's last active time.. [optional]  # noqa: E501
            windows ([JourneyTimeWindow]): time_window nodes: one or more time windows. A window with no day_of_week applies to every day. Required when relative_to is schedule_in_timezone; omit when it is last_active_time.. [optional]  # noqa: E501
            time_zone (str): time_window nodes: IANA timezone identifier used when the user's timezone is unavailable.. [optional]  # noqa: E501
            use_user_time_zone (bool, none_type): time_window nodes: when true, uses the user's timezone if available.. [optional]  # noqa: E501
            template_id (str): send_push, send_email, and send_sms nodes: UUID of the template to send.. [optional]  # noqa: E501
            iam_id (str): send_iam nodes: UUID of the in-app message to send.. [optional]  # noqa: E501
            user_ttl_seconds (int, none_type): send_iam nodes: optional time-to-live for the in-app message, in seconds.. [optional]  # noqa: E501
            webhook_id (str): send_webhook nodes: UUID of the webhook to send.. [optional]  # noqa: E501
            assignments ({str: (str,)}): tag nodes: tag key-value pairs to assign. An empty string value removes the tag. Keys are limited to 255 characters and values to 1024.. [optional]  # noqa: E501
            randomize_on_entry (bool, none_type): split_range nodes: when true, assigns each user to a branch at random on entry. Defaults to false.. [optional]  # noqa: E501
            branches ([JourneyBranch]): Branching nodes: nested branches. split_range requires 2-20 weighted branches that sum to 100. yes_no requires exactly 2 branches. wait_until requires 1-10 condition branches.. [optional]  # noqa: E501
            expiration (JourneyWaitUntilExpiration): [optional]  # noqa: E501
            concurrency_key (str, none_type): Optional optimistic-concurrency token. Pass the concurrency_key from a prior fetch to reject the update with 409 if the journey changed. Omit to skip the check. It is not merged onto the node.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """UpdateJourneyNodeRequest - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            client_node_id (str): Optional client-assigned identifier, unique within the journey. Use it to reference this node from elsewhere in the same request. Persisted and returned on reads.. [optional]  # noqa: E501
            annotation (str): Optional free-text label, up to 255 characters. Stored and returned as-is with no effect on journey behavior.. [optional]  # noqa: E501
            duration_seconds (int, none_type): wait nodes: seconds to hold the user. Minimum 60, maximum 31556952 (1 year).. [optional]  # noqa: E501
            relative_to (str): time_window nodes: schedule_in_timezone uses the configured windows; last_active_time holds relative to the user's last active time.. [optional]  # noqa: E501
            windows ([JourneyTimeWindow]): time_window nodes: one or more time windows. A window with no day_of_week applies to every day. Required when relative_to is schedule_in_timezone; omit when it is last_active_time.. [optional]  # noqa: E501
            time_zone (str): time_window nodes: IANA timezone identifier used when the user's timezone is unavailable.. [optional]  # noqa: E501
            use_user_time_zone (bool, none_type): time_window nodes: when true, uses the user's timezone if available.. [optional]  # noqa: E501
            template_id (str): send_push, send_email, and send_sms nodes: UUID of the template to send.. [optional]  # noqa: E501
            iam_id (str): send_iam nodes: UUID of the in-app message to send.. [optional]  # noqa: E501
            user_ttl_seconds (int, none_type): send_iam nodes: optional time-to-live for the in-app message, in seconds.. [optional]  # noqa: E501
            webhook_id (str): send_webhook nodes: UUID of the webhook to send.. [optional]  # noqa: E501
            assignments ({str: (str,)}): tag nodes: tag key-value pairs to assign. An empty string value removes the tag. Keys are limited to 255 characters and values to 1024.. [optional]  # noqa: E501
            randomize_on_entry (bool, none_type): split_range nodes: when true, assigns each user to a branch at random on entry. Defaults to false.. [optional]  # noqa: E501
            branches ([JourneyBranch]): Branching nodes: nested branches. split_range requires 2-20 weighted branches that sum to 100. yes_no requires exactly 2 branches. wait_until requires 1-10 condition branches.. [optional]  # noqa: E501
            expiration (JourneyWaitUntilExpiration): [optional]  # noqa: E501
            concurrency_key (str, none_type): Optional optimistic-concurrency token. Pass the concurrency_key from a prior fetch to reject the update with 409 if the journey changed. Omit to skip the check. It is not merged onto the node.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
