name: PIP Release

on:
  push:
    branches: [cd-pip-deploy]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true